version: '1'

ignore:
- .git
- env
- .env
- .tox
- node_modules
- vendor
- venv
- .venv
- ~/.pyenv
- ~/.rye
- ~/.vscode
- .vscode
- ~/.cache
- ~/.config
- ~/.local

rule_settings:
  enable:
  - default
  disable: []
  rule_types:
  - refactoring
  - suggestion
  - comment
  python_version: '3.12'
