"""
===========================
Create an AIA 94 Å response
===========================

This example demonstrates how to create a broadband imaging response for the
SDO/AIA 94 Å channel by combining a precomputed CHIANTI line list with the
wavelength response and plate scale from `aiapy`.

Unlike a spectrograph, an imager integrates over its whole bandpass, so the
main product is a temperature response rather than a line profile. We compute
that response directly, then use :func:`muse.instrument.create_spectral_response`
to combine every transition into one wavelength-space component.

.. warning::

    This example requires the optional ``aiapy`` package. Install it with
    ``pip install aiapy`` before running the script.
"""

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

import astropy.constants as const
import astropy.units as u

from muse.data import fetch_example_data
from muse.instrument import create_spectral_response

try:
    from aiapy.response import Channel
except ImportError:
    msg = "aiapy is required for this example, install it with `pip install aiapy`"
    raise ImportError(msg) from None

##############################################################################
# `aiapy` provides the wavelength-dependent effective area and detector gain
# together as ``wavelength_response``. Dividing by the photon energy converts
# CHIANTI's energy radiance to photons, and multiplying by the AIA plate scale
# converts per-steradian radiance to the signal in one detector pixel.
# With no ``obstime``, this uses the baseline calibration without a
# time-dependent degradation correction.

channel = Channel(94 * u.angstrom)
photon_energy = (const.h * const.c / channel.wavelength / u.ph).to(u.erg / u.ph)
radiometric_conversion_quantity = (channel.wavelength_response() * channel.plate_scale / photon_energy).to(
    u.cm**2 * u.DN * u.sr / (u.erg * u.pix)
)
radiometric_conversion = xr.DataArray(
    radiometric_conversion_quantity.value,
    dims="wavelength",
    coords={"wavelength": ("wavelength", channel.wavelength.to_value(u.AA), {"units": str(u.AA)})},
    attrs={"units": str(radiometric_conversion_quantity.unit)},
).sel(wavelength=slice(84, 106))

plt.figure()
radiometric_conversion.plot()
plt.yscale("log")
plt.title("AIA 94 Å radiometric conversion")

##############################################################################
# The 94 Å channel is dominated by iron lines (Fe XVIII in flares and
# hot active-region plasma, Fe VIII-Fe X at cooler temperatures), so we keep
# the line list to iron. It was generated by the
# :ref:`CHIANTI preparation example
# <sphx_glr_generated_gallery_other_instruments_skip_prepare_chianti_line_lists.py>`.

line_list_file = fetch_example_data("aia_chianti_line_list_94_Fe_sun_coronal_2021_chianti.nc")
line_list = xr.load_dataset(line_list_file, engine="h5netcdf")
print(line_list)

##############################################################################
# To include lines from every sufficiently abundant element instead of only
# iron, generate the line list locally with CHIANTI as follows:
#
# .. note::
#
#     This code snippet is not run.
#     We still only use the line list created in the previous step.
#
# .. code-block:: python
#
#     temperature = xr.DataArray(10 ** np.arange(4.5, 8.0, 0.1) * u.K, dims="logT")
#     pressure = xr.DataArray([3e15] * u.K / u.cm**3, dims="pressure")
#     abundance = "sun_coronal_2021_chianti"
#     line_list = create_chianti_line_list(
#         temperature=temperature,
#         pressure=pressure,
#         abundance=abundance,
#         wavelength_range=[84, 106] * u.AA,
#         minimum_abundance=1e-6,
#     )
#
# The response calculation below would then automatically include every line
# in that list.
#
# But we will continue with our more focused line list.

##############################################################################
# The temperature response of the channel is the sum over every line of its
# contribution function weighted by the AIA radiometric conversion at that
# line's wavelength. This direct integration avoids sampling narrow line
# profiles on a wavelength grid.
#
# The result shows the familiar bimodal shape of the 94 Å channel, peaking
# around logT of about 6.0 (Fe X) and about 6.8 (Fe XVIII). It is the line
# contribution only: a quantitative full-passband calculation must also
# include free-free, free-bound, and two-photon continuum emission.

conversion_at_lines = radiometric_conversion.interp(wavelength=line_list.wavelength).fillna(0.0).drop_vars("wavelength")
temperature_response = (line_list.gofnt * conversion_at_lines).sum(dim="trans_index")
temperature_response.attrs["units"] = str(u.Unit(line_list.gofnt.attrs["units"]) * radiometric_conversion_quantity.unit)
plt.figure()
temperature_response.isel(pressure=0).plot()
plt.yscale("log")
plt.ylim(temperature_response.max().item() / 1e4, None)
plt.ylabel(f"Line-only response [{temperature_response.attrs['units']}]")
plt.title("AIA 94 Å temperature response (Fe lines only)")

##############################################################################
# Which lines make up that response? Grouping the per-transition contributions
# by ion shows that the two peaks have very different origins. The hot peak is
# almost entirely one transition, Fe XVIII 93.932 Å, whereas the cool peak is
# the sum of thousands of weaker Fe VIII-Fe XII lines that no single transition
# dominates. For an imager these are not "contaminants" to be removed; they
# *are* the cool response of the channel.

line_contribution = (line_list.gofnt * conversion_at_lines).isel(pressure=0)
response_by_ion = line_contribution.groupby(line_list.spectroscopic_name).sum()
response_by_ion.attrs["units"] = temperature_response.attrs["units"]
# Name the ions that reach at least 2% of the peak response, ordered by where they peak.
named_ions = response_by_ion.spectroscopic_name[response_by_ion.max(dim="logT") > temperature_response.max() / 50]
named_ions = named_ions.sortby(response_by_ion.sel(spectroscopic_name=named_ions).idxmax(dim="logT"))
plt.figure()
temperature_response.isel(pressure=0).plot(color="k", lw=2, label="all lines")
for ion in named_ions.values:
    response_by_ion.sel(spectroscopic_name=ion).plot(label=str(ion))
response_by_ion.drop_sel(spectroscopic_name=named_ions.values).sum(dim="spectroscopic_name").plot(
    ls="--", color="gray", label="other ions"
)
plt.yscale("log")
plt.ylim(temperature_response.max().item() / 1e4, None)
plt.ylabel(f"Line-only response [{temperature_response.attrs['units']}]")
plt.legend(fontsize=8)
plt.title("AIA 94 Å temperature response by ion")

##############################################################################
# Passing ``main_lines=None`` requests no named lines. Together with
# ``include_contaminants=True``, this accumulates every transition into one
# ``contaminants`` component, which is the natural representation for an
# imager that does not resolve individual spectral lines: all 26,000
# transitions above collapse into a single wavelength-space profile that a
# synthesis can sample, while the direct sum remains the quantitative
# broadband temperature response.

response = create_spectral_response(
    line_list,
    np.arange(91.0, 97.02, 0.02) * u.AA,
    main_lines=None,
    include_contaminants=True,
)
conversion_on_grid = (
    radiometric_conversion.interp(wavelength=response.wavelength_grid).fillna(0.0).drop_vars("wavelength")
)
response_unit = u.Unit(response.spectral_response.attrs["units"]) * radiometric_conversion_quantity.unit
scaled_response = (response.spectral_response * conversion_on_grid).assign_attrs(
    {**response.spectral_response.attrs, "units": str(response_unit)}
)
response = response.assign(spectral_response=scaled_response)
print(response)

plt.show()
