"""
===========================
Create an AIA 94 Å response
===========================

This example demonstrates how to create a broadband imaging response for the
SDO/AIA 94 Å channel by combining a precomputed CHIANTI line list with the
wavelength response and plate scale from `aiapy`.

Unlike a spectrograph, an imager integrates over its whole bandpass, so the
main product is a temperature response rather than a line profile. We build
that directly from the line list, then use
:func:`muse.instrument.create_spectral_response` to resolve the dominant
contributors in wavelength and Doppler velocity.

It requires `aiapy` (``pip install aiapy``) for the instrument response.
"""

import matplotlib.pyplot as plt
import numpy as np
import xarray as xr

import astropy.constants as const
import astropy.units as u

from muse.data import fetch_example_data
from muse.instrument import create_spectral_response

try:
    from aiapy.response import Channel
except ImportError:
    msg = "aiapy is required for this example, install it with `pip install aiapy`"
    raise ImportError(msg) from None

##############################################################################
# `aiapy` provides the wavelength-dependent effective area and detector gain
# together as ``wavelength_response``. Dividing by the photon energy converts
# CHIANTI's energy radiance to photons, and multiplying by the AIA plate scale
# converts per-steradian radiance to the signal in one detector pixel.
# With no ``obstime``, this uses the baseline calibration without a
# time-dependent degradation correction.

channel = Channel(94 * u.angstrom)
photon_energy = (const.h * const.c / channel.wavelength / u.ph).to(u.erg / u.ph)
radiometric_conversion_quantity = (channel.wavelength_response() * channel.plate_scale / photon_energy).to(
    u.cm**2 * u.DN * u.sr / (u.erg * u.pix)
)
radiometric_conversion = xr.DataArray(
    radiometric_conversion_quantity.value,
    dims="wavelength",
    coords={"wavelength": ("wavelength", channel.wavelength.to_value(u.AA), {"units": str(u.AA)})},
    attrs={"units": str(radiometric_conversion_quantity.unit)},
).sel(wavelength=slice(84, 106))

plt.figure()
radiometric_conversion.plot()
plt.yscale("log")
plt.title("AIA 94 Å radiometric conversion")

##############################################################################
# The 94 Å channel is dominated by iron lines (Fe XVIII in flares and
# hot active-region plasma, Fe VIII-Fe X at cooler temperatures), so we keep
# the line list to iron. It was generated by the
# :ref:`CHIANTI preparation example
# <sphx_glr_generated_gallery_other_instruments_skip_prepare_chianti_line_lists.py>`.

abundance = "sun_coronal_2021_chianti"
line_list_file = fetch_example_data("aia_chianti_line_list_94_Fe_sun_coronal_2021_chianti.nc")
line_list = xr.load_dataset(line_list_file, engine="h5netcdf")
line_list = line_list.assign(wavelength=line_list.wavelength.assign_attrs(units=str(u.AA)))
print(line_list)

##############################################################################
# To include lines from every sufficiently abundant element instead of only
# iron, generate the line list locally with CHIANTI as follows (this block is
# documentation only and is not executed by the gallery):
#
# .. code-block:: python
#
#     from muse.instrument import create_chianti_line_list
#
#     temperature = xr.DataArray(10 ** np.arange(4.5, 8.0, 0.1) * u.K, dims="logT")
#     pressure = xr.DataArray([3e15] * u.K / u.cm**3, dims="pressure")
#     line_list = create_chianti_line_list(
#         temperature=temperature,
#         pressure=pressure,
#         abundance=abundance,
#         wavelength_range=[84, 106] * u.AA,
#         minimum_abundance=1e-6,
#     )
#
# The temperature-response calculation below will then include every line in
# that list. For an all-line synthesis, pass ``main_lines=[]`` and
# ``include_contaminants=True`` to ``create_spectral_response``; this combines
# all transitions into one band component instead of materializing a separate
# response for every line.

##############################################################################
# The temperature response of the channel is the sum over every line of its
# contribution function weighted by the AIA radiometric conversion at that
# line's wavelength. Note that this is the line contribution only: the continuum
# (free-free, free-bound, two-photon) is not included, so a quantitative full
# passband calculation must include those emissivity components as well.
#
# The result shows the familiar bimodal shape of the 94 Å channel,
# peaking around logT of about 6.0 (Fe X) and about 6.8 (Fe XVIII).

conversion_at_lines = radiometric_conversion.interp(wavelength=line_list.wavelength).fillna(0.0).drop_vars("wavelength")
temperature_response = (line_list.gofnt * conversion_at_lines).sum(dim="trans_index")
temperature_response.attrs["units"] = str(u.Unit(line_list.gofnt.attrs["units"]) * radiometric_conversion_quantity.unit)
plt.figure()
temperature_response.isel(pressure=0).plot()
plt.yscale("log")
plt.ylim(temperature_response.max().item() / 1e4, None)
plt.ylabel(f"Line-only response [{temperature_response.attrs['units']}]")
plt.title("AIA 94 Å temperature response (Fe lines only)")

##############################################################################
# To see which lines drive that shape, we rank the transitions by their
# radiometrically weighted peak contribution and build a Doppler-resolved
# spectral response for the strongest ones. Repeated transitions sharing a
# ``full_name`` are summed by ``create_spectral_response``.


peak_weight = (line_list.gofnt.isel(pressure=0) * conversion_at_lines).max(dim="logT")
ranked = line_list.full_name.values[np.argsort(-peak_weight.values)]
# We deliberately only use the top 5 otherwise the full band would
# compute 1353983 profiles with contaminants.
main_lines = list(dict.fromkeys(str(name) for name in ranked))[:5]
print(f"Strongest contributors: {main_lines}")

response = create_spectral_response(
    line_list,
    np.arange(91.0, 97.0, 0.02) * u.AA,
    main_lines=main_lines,
    doppler_velocity=np.arange(-300, 320, 20) * u.km / u.s,
    # This can be slow.
    include_contaminants=True,
)
conversion_on_grid = (
    radiometric_conversion.interp(wavelength=response.wavelength_grid).fillna(0.0).drop_vars("wavelength")
)
response_unit = u.Unit(response.spectral_response.attrs["units"]) * radiometric_conversion_quantity.unit
scaled_response = (response.spectral_response * conversion_on_grid).assign_attrs(
    {**response.spectral_response.attrs, "units": str(response_unit)}
)
response = response.assign(spectral_response=scaled_response)
print(response)

##############################################################################
# Finally, the per-line temperature sensitivity within the bandpass.

line_total = response.spectral_response.isel(pressure=0).sel(doppler_velocity=0).integrate("wavelength_grid")
line_total.attrs["units"] = str(response_unit * u.AA)
plt.figure()
for line in line_total.line.values:
    line_total.sel(line=line).plot(label=str(line))
plt.yscale("log")
plt.ylim(line_total.max().item() / 1e4, None)
plt.title("AIA 94 Å per-line temperature sensitivity")
plt.legend()

plt.show()
